version: 2.1

commands:
  install_deps:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
            - v1-npm-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}

  test:
    steps:
      - run: npm run test

  build:
    steps:
      - run: npm run build

jobs:
  "node-8-test":
    docker:
      - image: circleci/node:8
    steps:
      - install_deps
      - test

  "node-8-build":
    docker:
      - image: circleci/node:8
    steps:
      - install_deps
      - build

  "node-10-test":
    docker:
      - image: circleci/node:10
    steps:
      - install_deps
      - test

  "node-10-build":
    docker:
      - image: circleci/node:10
    steps:
      - install_deps
      - build
      - persist_to_workspace:
          root: ./
          paths:
            - lib

  "node-12-test":
    docker:
      - image: circleci/node:12
    steps:
      - install_deps
      - build

  "node-12-build":
    docker:
      - image: circleci/node:12
    steps:
      - install_deps
      - test

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run deploy

workflows:
  version: 2
  matrix:
    jobs:
      - "node-8-test"
      - "node-8-build"
      - "node-10-test"
      - "node-10-build"
      - "node-12-test"
      - "node-12-build"
      - deploy:
          requires:
            - "node-8-test"
            - "node-8-build"
            - "node-10-test"
            - "node-10-build"
            - "node-12-test"
            - "node-12-build"
