parameters:
  tag:
    default: '10'
    type: string
  run-main-workflow:
    default: false
    type: boolean
  run-deploy-job:
    default: false
    type: boolean

executors:
  node:
    docker:
      - image: circleci/node:<< pipeline.parameters.tag >>

version: 2.1
jobs:
  install_deps:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ .checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-
            - v1-npm-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-{{ .Branch }}-{{ .checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run test

  build:
    executor: node

    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run build

      - when:
          condition: << pipeline.parameters.run-deploy-job >>
          steps:
            - attach_workspace:
                root: ./
                paths:
                  - lib
                  - node_modules

  deploy:
    docker:
      - image: circleci/node:<< pipeline.parameters.tag >>
    steps:
      - when:
          condition: << pipeline.parameters.run-deploy-job >>
          steps:
            - checkout
            - attach_workspace:
                at: ./
            - run: npm run deploy
      - unless:
          condition: << pipeline.parameters.run-deploy-job >>
          steps:
            - run: echo "No deployment on << pipeline.parameters.tag >>"

  trigger-jobs:
    machine:
      image: ubuntu-1604:201903-01
    parameters:
      pipeline-param-map:
        type: string
    steps:
      - run:
          name: Trigger main worflow
          command: |
            VCS_TYPE=$(echo ${CIRCLE_BUILD_URL} | cut -d '/' -f 4)

            curl -u ${CIRCLE_TOKEN}: -X POST --header "Content-Type: application/json" -d "{
              \"branch\": \"${CIRCLE_BRANCH}\",
              \"parameters\": << parameters.pipeline-param-map >>
            }" "https://circleci.com/api/v2/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline"

workflows:
  version: 2
  trigger-jobs:
    unless: << pipeline.parameters.run-main-workflow >>
    jobs:
      - trigger-jobs:
          pipeline-param-map: |
            {\"run-main-workflow\": true, \"tag\":\"8\"}
      - trigger-jobs:
          pipeline-param-map: |
            {\"run-main-workflow\": true, \"tag\":\"10\", \"run-deploy\": true \}
      - trigger-jobs:
          pipeline-param-map: |
            {\"run-main-workflow\": true, \"tag\":\"latest\"}

  main:
    when: << pipeline.parameters.run-main-workflow >>
    jobs:
      - build:
          name: << pipeline.parameters.tag >>
      - test
      - deploy:
          requires:
            - build
            - test
